"""Interactive dashboard for attendance CSV files."""

from __future__ import annotations

import io
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from dashboard.analytics import (  # noqa: E402
    AttendanceDataError,
    count_by_date,
    count_by_person,
    parse_attendance_csv,
    summarise_attendance,
)

SAMPLE_FILE = REPOSITORY_ROOT / "examples" / "sample_attendance.csv"

st.set_page_config(
    page_title="Face Recognition Attendance Dashboard",
    page_icon="🎯",
    layout="wide",
)

st.markdown(
    """
    <style>
    .block-container {padding-top: 2rem; padding-bottom: 3rem;}
    [data-testid="stMetric"] {
        border: 1px solid rgba(125, 151, 255, 0.24);
        border-radius: 14px;
        padding: 16px;
        background: rgba(44, 57, 94, 0.18);
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("🎯 Face Recognition Attendance Dashboard")
st.caption(
    "Explore the CSV records generated by the local webcam recognition app. "
    "This dashboard does not upload or process biometric face images."
)

with st.sidebar:
    st.header("Attendance data")
    uploaded_file = st.file_uploader(
        "Upload a daily or combined attendance CSV",
        type="csv",
        help="Required columns: name, date, time and face_distance.",
    )
    st.info(
        "No file selected? The dashboard uses privacy-safe synthetic sample data."
    )

try:
    if uploaded_file is None:
        with SAMPLE_FILE.open("r", encoding="utf-8") as sample_file:
            records = parse_attendance_csv(sample_file)
        source_label = "Synthetic sample data"
    else:
        text = uploaded_file.getvalue().decode("utf-8-sig")
        records = parse_attendance_csv(io.StringIO(text))
        source_label = uploaded_file.name
except (AttendanceDataError, UnicodeDecodeError) as exc:
    st.error(f"Could not load attendance data: {exc}")
    st.stop()

all_names = sorted({record.name for record in records})
all_dates = sorted({record.date.isoformat() for record in records})

with st.sidebar:
    selected_names = st.multiselect("People", all_names, default=all_names)
    selected_dates = st.multiselect("Dates", all_dates, default=all_dates)
    st.caption(f"Source: {source_label}")

filtered_records = [
    record
    for record in records
    if record.name in selected_names and record.date.isoformat() in selected_dates
]
if not filtered_records:
    st.warning("No records match the selected filters.")
    st.stop()

summary = summarise_attendance(filtered_records)
metric_columns = st.columns(4)
metric_columns[0].metric("Attendance records", summary["records"])
metric_columns[1].metric("Unique people", summary["people"])
metric_columns[2].metric("Attendance days", summary["days"])
average_distance = summary["average_distance"]
metric_columns[3].metric(
    "Average face distance",
    f"{average_distance:.3f}" if average_distance is not None else "N/A",
    help="Lower distance generally indicates a closer encoding match; it is not a probability.",
)

st.divider()
trend_tab, people_tab, records_tab = st.tabs(
    ["Daily trend", "People", "Attendance records"]
)

with trend_tab:
    daily_counts = pd.DataFrame(
        count_by_date(filtered_records), columns=["date", "attendance"]
    ).set_index("date")
    st.subheader("Attendance by date")
    st.bar_chart(daily_counts, color="#4F8BF9")

with people_tab:
    people_counts = pd.DataFrame(
        count_by_person(filtered_records), columns=["name", "attendance"]
    ).set_index("name")
    st.subheader("Attendance by person")
    st.bar_chart(people_counts, horizontal=True, color="#22C55E")

with records_tab:
    table = pd.DataFrame(record.as_dict() for record in filtered_records)
    table = table.sort_values("timestamp", ascending=False).drop(columns="timestamp")
    table = table.rename(
        columns={
            "name": "Name",
            "date": "Date",
            "time": "Time",
            "face_distance": "Face distance",
        }
    )
    st.subheader("Validated attendance records")
    st.dataframe(table, use_container_width=True, hide_index=True)
    st.download_button(
        "Download filtered CSV",
        data=table.to_csv(index=False).encode("utf-8"),
        file_name="filtered_attendance.csv",
        mime="text/csv",
    )

st.caption(
    "Educational portfolio project. Obtain consent before using face recognition "
    "and independently verify high-stakes attendance decisions."
)
